// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh5CbcWxzeUMZIqtRw7qw3-ZSuLD1SJCk',
    appId: '1:913192088188:web:4d9cac6084a175d41d4ff9',
    messagingSenderId: '913192088188',
    projectId: 'medicine-app-9cf7c',
    authDomain: 'medicine-app-9cf7c.firebaseapp.com',
    storageBucket: 'medicine-app-9cf7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArfgZSYdBw-Ghg_ACyv6-sMmwGOBwbeJE',
    appId: '1:913192088188:android:6485c2817dd4d3731d4ff9',
    messagingSenderId: '913192088188',
    projectId: 'medicine-app-9cf7c',
    storageBucket: 'medicine-app-9cf7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAKUFNJrTpXVXOiPfYmDU_QDdY0wMMXoA',
    appId: '1:913192088188:ios:b6dfcf62f91af1d11d4ff9',
    messagingSenderId: '913192088188',
    projectId: 'medicine-app-9cf7c',
    storageBucket: 'medicine-app-9cf7c.appspot.com',
    iosBundleId: 'com.example.medicinapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAKUFNJrTpXVXOiPfYmDU_QDdY0wMMXoA',
    appId: '1:913192088188:ios:60fef995dbbac5c61d4ff9',
    messagingSenderId: '913192088188',
    projectId: 'medicine-app-9cf7c',
    storageBucket: 'medicine-app-9cf7c.appspot.com',
    iosBundleId: 'com.example.medicinapp.RunnerTests',
  );
}
